### ISSUE TITLE
Uncaught Error: Call to undefined function each() in PHP 8

### ISSUE THREAD

**Issue by augustjanse** [kodeclan/phpfmt#4]
Description:
Running `fmt.phar` with PHP 8 fails without doing anything.

Failing code:
```
august@foo:/var/www/bar$ php ~/fmt.phar --psr2 --indent_with_space=4 index.php
```

Expected result:
```
Formatting ...
.
 0 files untouched (cache hit)
 1 files total
Took 0.06s
```

Actual result:
```
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 5513
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6355
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6472
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6512
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6520
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6532
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6537
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 7284
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 8707
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 8710
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 9956
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 11244
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 11264
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 11288
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 11823
Formatting ...
.PHP Fatal error:  Uncaught Error: Call to undefined function each() in phar:///home/august/fmt.phar/fmt.stub.php:4194
Stack trace:
#0 phar:///home/august/fmt.phar/fmt.stub.php(1655): TwoCommandsInSameLine->format()
#1 phar:///home/august/fmt.phar/fmt.stub.php(12422): BaseCodeFormatter->formatCode()
#2 /home/august/fmt.phar(10): include('...')
#3 {main}
  thrown in phar:///home/august/fmt.phar/fmt.stub.php on line 4194
```

Your configuration:
`fmt.phar` downloaded from repo root.

```
PHP 8.0.1 (cli) (built: Jan 13 2021 08:22:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.1, Copyright (c), by Zend Technologies
```

Works with warning for `php7.4`:
```
august@foo:/var/www/bar$ php7.4 ~/fmt.phar --psr2 --indent_with_space=4 index.php
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 5513
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6355
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6472
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6512
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6520
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6532
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 6537
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 7284
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 8707
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 8710
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 9956
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 11244
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 11264
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 11288
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///home/august/fmt.phar/fmt.stub.php on line 11823
Formatting ...
.
 0 files untouched (cache hit)
 1 files total
Took 0.06s
```

**Comment by ilonashairstyling** [comment]
Any update on this one please? I've simular issue.

**Comment by augustjanse** [comment]
Looks dead (#3). I switched to php-cs-fixer.
